name: glaft 

channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - numpy
  - scipy
  - shapely
  - geopandas
  - rasterio
  - matplotlib
  - pandas
  - jupyter-book=0.12
  - matplotlib
  - pip
  - seaborn
  - cmcrameri
  - tabulate
  - scikit-learn